Description: YAML Configuration file for unit test in SCuBA
ProductNames:
# - teams
# - exo
# - defender
 - aad
# - sharepoint
# - onedrive
M365Environment: commercial
OPAPath: .
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports
AnObject:
  name: MyObjectName
Aad:
# All AAD specific variables go here
  Common:
    # Common variables can be applied to any or all relevant policies
      CapExclusions:
        # These exclusions will be applied to all policies checking conditional access policies
        # in addition to any individual policy exclusions
      - Group:
        - BackupGroup
  Policy2_1:
    CapExclusions:
    # The exclusions could include both groups and users
      Groups:
      # "TEST CAP EXclusions Group 1" from y2zj1 E5 tenant
        - 08adb07a-956f-450e-b41c-81e92e3db2c4
      Users:
      # "Test CAP Exclusions User 1" from y2zj1 E5 tenant
       - fc29f4a8-2b27-4d1e-898e-cfacb98bd8f8
#SharePoint:
#Teams:

# Rego code examples to reference a config file variable value
# input.scuba_config.Aad.Common.CapExclusions.Group
# input.scuba_config.GlobalVars.AllProductVar
# input.scuba_config.Aad.Policy2_1.CapExclusions.Group
